---
title: "developement"
subtitle: "The internals of postcodElapse."
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This document will walk you trough how postcodElapse takes a postcode and estimates
air pollutant concentrations for that postcode. Assumed is some knowledge about 
the use of postcodElapse and programming. I also recommend keeping the source code
at hand.

## Code walk
Lets say you invoked `postcodElapse()` in the manner below:
``` r
library(postcodElapse)

postcodElapse("9713GZ", "./bag-light.gpkg")
#> Guessed db type to be: BAG
#>   postcode n BCFULL_avg NO2FULL_avg O3FULLa_avg O3FULLc_avg O3FULLw_avg
#> 1   9713GZ 2    1.76874    29.62822    61.81072    45.75105    78.72445
#>   PM25FULLt_avg BCFULL_min NO2FULL_min O3FULLa_min O3FULLc_min O3FULLw_min
#> 1      15.05896   1.768234     29.0291    61.77345    45.72406    78.30206
#>   PM25FULLt_min BCFULL_max NO2FULL_max O3FULLa_max O3FULLc_max O3FULLw_max
#> 1      14.93575   1.769246    30.22734      61.848    45.77803    79.14684
#>   PM25FULLt_max
#> 1      15.18216
```

The `postcodElapse()` first does some sanity checks and immediately calls 
`loadElapse()` with give the path to ELAPSE, which may be missing.
``` r
  if(!file.exists(db_path)) {
    stop(db_path, " does not exist.")
  }
  if(!tools::file_ext(db_path) == "gpkg") {
    stop(db_path, " Is not an gpkg file.")
  }

  elapse <- loadElapse(elapse_path)
```

`loadElapse()` if it finds the path to elapse is missing it grabs the path to the 
included one stored in `postcodElapse/inst/ELAPSE.tif` And loads it with 
`terra::rast()`. The included ELAPSE is special in the sense that its coordinate
-system was transformed to equal EPSG:28992, to speed up processing.

`postcodElapse/R/helpers.R`
``` r
loadElapse <- function(path) {
  # No path, get it for the internal ELAPSE.
  if(missing(path)) {
    path <- system.file("ELAPSE.tif", package = "postcodElapse")
  }
  if(!file.exists(path)) {
   stop(path, " Does not exist.")
  }
  
  elapse_stack <- terra::rast(path)
  
  return(elapse_stack)
}
```

After returning ELAPSE the given database is checked with the `checkDb()` helper,
which is internal only. It works by examining the metadata of the given .gpkg using
sf::st_layers() and checking if it matches a list. Hashing would be better if is
constant internal formatting of R-objects is different between platforms. Which 
isn't the case.

`postcodElapse/R/helpers.R`
``` r
checkDb <- function(path) {
  # sf::st_layers() gives metadata about the given gpkg, here it is used to
  # determine the type of the database, if you want to add another DB just check
  # the output off sf::st_layers() and add another if case.
  tryCatch({
    metadata <- sf::st_layers(path)
  }, error = function(e) {
    stop("Failed to open database: ", path)
  })

  # Do the test
  if(identical(metadata$name, c("pand", "verblijfsobject", "ligplaats", "standplaats", "woonplaats"))) {
    type <- "BAG"
  } else if(identical(metadata$name, c("postcode6"))) {
    type <- "PC6"
  } else {
    stop("Unable to determine type of database: ", path)
  }

  message("Guessed db type to be: ", type)

  return(type)
}
```

Now we know that BAG is the provided db the user gave `pollutionFormBag()` is chosen 
to run with the postcodes, db_path, elapse_path passed down in addition to the 
pass_db_check flag. In `pollutionFromBag()` we check if pass_db_check flag is set
to well not run `checkDb()` because we already did that, saving 3seconds.
``` r
  if(db_type == "BAG") {
    postcode_pollution <- pollutionFromBag(postcodes,
                                           bag_path = db_path,
                                           elapse_path,
                                           pass_db_check = TRUE)
```



``` r
    # Of course multiple homes exist per postcode, so summarize.
    postcode_pollution_stats <- postcode_pollution |>
      dplyr::group_by(postcode) |>
      dplyr::summarise_at(tools::file_path_sans_ext(terra::names(elapse)),
                          list(avg = mean, min = min, max = max))

    # Adding how many homes per postcodes just makes sense
    postcode_pollution_stats <- postcode_pollution |>
      dplyr::count(postcode) |>
      dplyr::inner_join(postcode_pollution_stats, by = dplyr::join_by(postcode))

    # In case we miss postcodes warn about it.
    count_given_postcodes <- length(postcodes)
    count_found_postcodes <- nrow(postcode_pollution_stats)
    if(count_found_postcodes != count_given_postcodes) {
      warning("Found ", count_found_postcodes, " postcodes of the given ",
              count_given_postcodes, ".")
    }

  }
```
